"""Update Blog Model Migration

Revision ID: a855999bce36
Revises: b072e251bb84
Create Date: 2022-05-20 23:21:51.476043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a855999bce36'
down_revision = 'b072e251bb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('desc', sa.String(), nullable=True))
    op.drop_column('blogs', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'desc')
    # ### end Alembic commands ###
